<<<<<<< HEAD
app = "itadori-dashboard"
primary_region = "gru"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
auto_stop_machines = "stop"
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
=======
# fly.toml app configuration file generated for itadoritrue on 2026-03-25T13:28:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'itadoritrue'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
>>>>>>> 5fe30cf652c3f612dd1ae985b09665ca3be49922
